### ISSUE TITLE
Create session manager

### ISSUE THREAD

**Issue by girba** [feenkcom/gt4gemstone-old#1]
We need a tool that allows us to:
- view existing sessions
- create a new session
- select the active session
- inspector/playground on the active session

**Comment by chisandrei** [comment]
There is support for a basic session manager. However the manager requires explicit files on disk describing how to connect to a gemstone session. There files are not really needed and should be removed

**Comment by chisandrei** [comment]
There exists now a full version of a session manager. It allows to create, login/logout and remove sessions and can also create/delete session descriptions.
