### ISSUE TITLE
Add a playground to each inspector pane

### ISSUE THREAD

**Issue by girba** [feenkcom/gt4gemstone-old#17]
Right now, we only serialize basic presentations. For the playground in each inspector pane, we can either rely on this and add a separate tab, or make it like in the Pharo inspector. In the latter case, we need to serialize a Tabulator.

**Comment by chisandrei** [comment]
Each object has now an Evaluator presentation. Code can be executed either remote or in the local image. Next step is to embed the Raw and the Evaluator presentations into a tabulator

**Comment by girba** [comment]
I would consider this done for now.
