### ISSUE TITLE
Introduce a dedicated presentation provider for special classes

### ISSUE THREAD

**Issue by girba** [feenkcom/gt4gemstone-old#18]
The inspector extensions rely on method extensions. However, in Gemstone, core classes require special privileges. To not require the developer to have those privileges, we should introduce a separate mechanism through which to define these extensions for special classes (such as GsNMethod).

**Comment by chisandrei** [comment]
For special classes a subclass of GtGsInspectorProxy can be created and added to #proxyMappings.
