### ISSUE TITLE
broken instance/class view

### ISSUE THREAD

**Issue by dalehenrich** [feenkcom/gt4gemstone-old#44]
pharo5.0 commit a2b75e4:

![image](https://cloud.githubusercontent.com/assets/623951/24727697/ceca59ae-1a0b-11e7-8a0a-06c8a6b4c961.png)

No methods visible for selected class on either Instance or Class side.  On class-side only `conversions` protocol is shown (empty) and on instance-side  an empty `accessing` protocol is show regardless of selected class ...

Prior to opening the category browser, I had opened a SymbolList browser, but didn't click around...

Now that I've opened a SymbolList browser the protocols were working until I hit a walk back:

![image](https://cloud.githubusercontent.com/assets/623951/24727933/b4b26f24-1a0c-11e7-8237-585b2d8922fd.png)

and now I see that GtGsBareClient is on the stack, but I have logged into a stone with tODE included so it probably shouldn't be using the bare client? 

Probably need a way to specify whther or not you need a bare client when using the Sessions Handler? Nice to (potentially) be able to open different browsers from Sessions Handler...

**Comment by dalehenrich** [comment]
Perhaps something in the playground title and/or the SessionsHandler listing could indicate whether or not a bare client is being used or not?

**Comment by chisandrei** [comment]
Regarding the client, right now you can just change the client globally using `GtGsSessionsLifecycleHandler defaultClientType: GtGsMinimalClient name.` Better would be to also add an explicit setting in the settings browser.

**Comment by dalehenrich** [comment]
even better would be an menu on the sessions handler itself to switch the global client ... after all isn't the session handler is the primary user of the defaultClientType?

**Comment by chisandrei** [comment]
I cannot reproduce this any longer using a BareClient.

**Comment by dalehenrich** [comment]
I've not seen this for awhile
