### ISSUE TITLE
how to recreate gt4gemstone client image

### ISSUE THREAD

**Issue by petr-fischer** [feenkcom/gt4gemstone-old#59]
Hello, I accidentaly saved my gt4gemstone client image and after next image run, every attempt to connect to the gemstone session, image crashes. So I want to recreate gemstone client image by:

```
deleteClient Gt4Gemstone
createClient -t pharo Gt4Gemstone -l -v Pharo5.0 -s devKit_33 -z $GS_HOME/shared/repos/gt4gemstone/.smalltalk.ston
```

and then, after `startClient Gt4Gemstone`, pharo image starts, but there is empty current session list in the session handler window.

- some listings
```
[gemstone@gemstone]$ clients
Installed Clients:
        tode1
          tode1.image   (client)
        Gt4Gemstone
          Gt4Gemstone.image     (client)

[gemstone@gemstone]$ stones
Installed Stones:
        3.3.0   devKit_33
Running Stones:
        Status       Version    Owner    Pid   Port   Started     Type       Name
        -------     --------- --------- ----- ----- ------------ ------      ----
        exists      3.3.0     gemstone   3075 43560 Sep 25 20:46 Stone       devKit_33
Running Netldis:
        Status       Version    Owner    Pid   Port   Started     Type       Name
        -------     --------- --------- ----- ----- ------------ ------      ----
        exists      3.3.0     gemstone   3278 41601 Sep 25 20:49 Netldi      devKit_33_ldi
```

**Comment by dalehenrich** [comment]
I replied on the gemstone-smalltalk@lists.gemtalksystems.com list, but I see that the question is here as well, so I will put my original response here:

> I think that it is normal for the sessions handler to be empty in a fresh image ... click on the table icon
>  ![epdmngpepofcflpb](https://user-images.githubusercontent.com/623951/30886902-eab01154-a2cd-11e7-9e85-a980fa3cb884.png)
> to select a stone, after which an entry is added to sessions handler and you are logged in ..

**Comment by petr-fischer** [comment]
I completely overlooked that button (I only tried the right mouse click on the empty session list)! Sorry, closing this issue :)
